// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRgdR7pHbMBigPO9ztrWOWopxXZCTZG98',
    appId: '1:245127140203:web:3ba8910edadc5a8557f22e',
    messagingSenderId: '245127140203',
    projectId: 'avocato-ac114',
    authDomain: 'avocato-ac114.firebaseapp.com',
    storageBucket: 'avocato-ac114.firebasestorage.app',
    measurementId: 'G-W9T7YEDKD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4w_VaLM3fAs0VA5g1cGwn_VCMf81mq40',
    appId: '1:245127140203:android:d7ce947136440ebd57f22e',
    messagingSenderId: '245127140203',
    projectId: 'avocato-ac114',
    storageBucket: 'avocato-ac114.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtTSaESs_Zdg8w14dmHN5B3144O2SrBWM',
    appId: '1:245127140203:ios:2584f4b9dc9b4ede57f22e',
    messagingSenderId: '245127140203',
    projectId: 'avocato-ac114',
    storageBucket: 'avocato-ac114.firebasestorage.app',
    iosBundleId: 'com.example.avocatooapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtTSaESs_Zdg8w14dmHN5B3144O2SrBWM',
    appId: '1:245127140203:ios:2584f4b9dc9b4ede57f22e',
    messagingSenderId: '245127140203',
    projectId: 'avocato-ac114',
    storageBucket: 'avocato-ac114.firebasestorage.app',
    iosBundleId: 'com.example.avocatooapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRgdR7pHbMBigPO9ztrWOWopxXZCTZG98',
    appId: '1:245127140203:web:e048b2893a5105e557f22e',
    messagingSenderId: '245127140203',
    projectId: 'avocato-ac114',
    authDomain: 'avocato-ac114.firebaseapp.com',
    storageBucket: 'avocato-ac114.firebasestorage.app',
    measurementId: 'G-DNDN7DT6B0',
  );

}